replicaCount: 1
dockerized: true
serviceId: "myservice"
clusterId: "mycluster"
loggerTypes: "Console;Debug"
loglevel: "Warning"

image1:
  ## Image location, NOT including the tag
  repository: skunklab/piraeus-mgmt-api
  ## Image tag
  tag: latest 
  pullPolicy: IfNotPresent
  
image2:
  ## Image location, NOT including the tag
  repository: skunklab/piraeus-websocket-gateway
  ## Image tag
  tag: latest 
  pullPolicy: IfNotPresent

service: 
  type: ClusterIP




