apiVersion: v1
items:
- apiVersion: cert-manager.io/v1alpha2
  kind: ClusterIssuer
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"cert-manager.io/v1alpha2","kind":"ClusterIssuer","metadata":{"annotations":{},"name":"letsencrypt-prod"},"spec":{"acme":{"email":"w.matt.long@gmail.com","http01":{},"privateKeySecretRef":{"name":"letsencrypt-prod"},"server":"https://acme-v02.api.letsencrypt.org/directory"}}}
    creationTimestamp: "2019-11-13T00:36:06Z"
    generation: 1
    name: letsencrypt-prod
    resourceVersion: "1321"
    selfLink: /apis/cert-manager.io/v1alpha2/clusterissuers/letsencrypt-prod
    uid: 9453c16f-05ad-11ea-ae6d-8a549fb9fbfc
  spec:
    acme:
      email: w.matt.long@gmail.com
      http01: {}
      privateKeySecretRef:
        name: letsencrypt-prod
      server: https://acme-v02.api.letsencrypt.org/directory
- apiVersion: cert-manager.io/v1alpha2
  kind: Certificate
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"cert-manager.io/v1alpha2","kind":"Certificate","metadata":{"annotations":{},"name":"tls-secret","namespace":"cert-manager"},"spec":{"acme":{"config":[{"domains":["jumpingbean8.eastus.cloudapp.azure.com"],"http01":{"ingressClass":"nginx"}}]},"dnsNames":["jumpingbean8.eastus.cloudapp.azure.com"],"issuerRef":{"kind":"ClusterIssuer","name":"letsencrypt-prod"},"secretName":"tls-secret"}}
    creationTimestamp: "2019-11-13T00:37:41Z"
    generation: 1
    name: tls-secret
    namespace: cert-manager
    resourceVersion: "1508"
    selfLink: /apis/cert-manager.io/v1alpha2/namespaces/cert-manager/certificates/tls-secret
    uid: cd1518f0-05ad-11ea-ae6d-8a549fb9fbfc
  spec:
    acme:
      config:
      - domains:
        - jumpingbean8.eastus.cloudapp.azure.com
        http01:
          ingressClass: nginx
    dnsNames:
    - jumpingbean8.eastus.cloudapp.azure.com
    issuerRef:
      kind: ClusterIssuer
      name: letsencrypt-prod
    secretName: tls-secret
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
