replicaCount: 1
dockerized: true
serviceId: "myservice"
clusterId: "mycluster"
loggerTypes: "Console;Debug"
loglevel: "Warning"

image:
  ## Image location, NOT including the tag
  repository: skunklab/piraeus-silo
  ## Image tag
  tag: latest 
  pullPolicy: IfNotPresent

service: 
  type: ClusterIP




